/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HeaderComponent {
        "logo": string;
        "menuItems": string;
        "rightSectionItems": string;
    }
    interface Header2Component {
        "logo": string;
        "menuItems": string;
        "rightSectionItems": string;
    }
}
declare global {
    interface HTMLHeaderComponentElement extends Components.HeaderComponent, HTMLStencilElement {
    }
    var HTMLHeaderComponentElement: {
        prototype: HTMLHeaderComponentElement;
        new (): HTMLHeaderComponentElement;
    };
    interface HTMLHeader2ComponentElement extends Components.Header2Component, HTMLStencilElement {
    }
    var HTMLHeader2ComponentElement: {
        prototype: HTMLHeader2ComponentElement;
        new (): HTMLHeader2ComponentElement;
    };
    interface HTMLElementTagNameMap {
        "header-component": HTMLHeaderComponentElement;
        "header2-component": HTMLHeader2ComponentElement;
    }
}
declare namespace LocalJSX {
    interface HeaderComponent {
        "logo"?: string;
        "menuItems"?: string;
        "rightSectionItems"?: string;
    }
    interface Header2Component {
        "logo"?: string;
        "menuItems"?: string;
        "rightSectionItems"?: string;
    }
    interface IntrinsicElements {
        "header-component": HeaderComponent;
        "header2-component": Header2Component;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "header-component": LocalJSX.HeaderComponent & JSXBase.HTMLAttributes<HTMLHeaderComponentElement>;
            "header2-component": LocalJSX.Header2Component & JSXBase.HTMLAttributes<HTMLHeader2ComponentElement>;
        }
    }
}
